/**
 * Semilla del módulo Compras tomada de "LARIS CATALAGO.xlsx" (2026-09-24).
 * Hoja 2 → piezas, insumos y presentaciones; Hoja 1 → productos de ejemplo con precios por proveedor.
 * Se corrigieron errores de dedo/codificación evidentes del Excel (p. ej. "BANDDA"→"BANDA", "P�LEA"→"POLEA").
 * Son catálogos editables desde la pantalla; esto solo es el arranque.
 */
export const SEED_PIEZAS: string[] = [
  "BALERO PISTA",
  "BALERO DOBLE",
  "BALERO CARDAN",
  "BALERO ESPIGA",
  "BANDA MOTRIZ",
  "BANDA SERPENTÍN",
  "BANDA CONICA",
  "CREMALLERA HIDRAULICA",
  "CREMALLERA ELECTRONICA",
  "MOTO VENTILADOR",
  "ABANICO P/FAN CLUTCH",
  "FAN CLUTCH VENTILADOR",
  "ROTULA INFERIOR",
  "ROTULA SUPERIOR",
  "TERMINAL EXTERIOR",
  "TERMINAL INTERIOR",
  "TENSOR HIDRÁULICO",
  "POLEA LOCA",
  "POLEA DAMPER",
  "POLEA COMPRESOR",
  "POLEA BOMBA DE AGUA",
  "POLEA POWER",
  "BUJIA COBRE",
  "BUJIA PLATINO",
  "BUJIA IRIDIO",
  "CABLES PARA BUJIA",
  "BOBINA",
  "ANFORA",
  "RADIADOR",
  "RECUPERADOR",
  "LLANTA RADIAL",
  "LLANTA CARGA",
  "LLANTA A/T",
  "FOCO LUZ BLANCA",
  "BOMBILLO LUZ AMBAR",
  "BOMBILLO STOP",
  "BOMBILLO REVERSA",
  "BOMBILLO DIRECCIONAL",
  "LIMPIA PARABRISAS",
  "BIRLO",
  "TUERCA",
  "BALATA DELANTERA",
  "BALATA TRASERA",
  "DISCO DE FRENO",
  "TAMBOR DE FRENOS",
  "CILINDRO MAESTRO",
  "CILINDRO ESCLAVO",
  "BOOSTER",
  "CILINDRO CLUTCH",
  "CLUTCH MECANICO",
  "CLUTCH HIDRÁULICO",
  "TAPETE",
  "CUBRE VOLANTE",
  "AMORTIGUADOR DELANTERO",
  "AMORTIGUADOR TRASERO",
  "BASE AMORTIGUADOR",
  "BUJE BARRA ESTABILIZADORA",
  "HORQUILLA DERECHA",
  "HORQUILLA IZQUIERDA",
  "BUJE FLOTANTE",
  "BUJE FRONTAL",
  "BUJE TRASERO",
  "BALERO MAZA",
  "FILTRO ACEITE SINTÉTICO",
  "FILTRO ACEITE MINERAL",
  "FILTRO AIRE MOTOR",
  "FILTRO A/C",
  "FILTRO GASOLINA",
  "FILTRO SEPARADOR",
  "FILTRO DIESEL",
  "MANGUERA AGUA SUPERIOR",
  "MANGUERA AGUA INFERIOR",
  "MANGUERA RETORNO DIESEL",
  "CRISTAL MEDALLON",
  "CRISTAL PARACHOQUES",
  "CRISTAL PTA IZQUIERDA",
  "CRISTAL PTA DERECHA",
  "TURBO DIÉSEL",
  "TURBO GASOLINA",
  "BOMBA POWER",
  "COLLARÍN CLUTCH",
  "HORQUILLA CLUTCH",
  "PRENSA CLUTCH"
];

export const SEED_INSUMOS: string[] = [
  "REFRIGERANTE VERDE",
  "REFRIGERANTE ROSA",
  "REFRIGERANTE LILA",
  "FLUIDO DIRECCIÓN HIDRÁULICA",
  "FLUIDO TRANSMISIÓN AUTOMÁTICA",
  "GRASA LITIO",
  "GRASA PARA BALERO",
  "ACEITE",
  "LIQUIDO DE FRENOS",
  "CARBUCLEAN",
  "AFLOJA TODO",
  "DESENGRASANTE",
  "PAÑO LIMPIADOR",
  "INFLALLANTAS",
  "DESODORANTE AMBIENTAL",
  "LIQUIDO AFINACION"
];

/** Unidades de medida / presentaciones: [nombre, abreviatura]. */
export const SEED_UNITS: Array<[string, string]> = [
  ['Pieza', 'PZA'], ['Litro', 'L'], ['Medio litro', '1/2 L'], ['1/4 de litro', '1/4 L'], ['Galón', 'GAL'],
  ['Cubeta', 'CUB'], ['Garrafa', 'GFA'], ['Juego', 'JGO'], ['Servicio', 'SERV'],
];

export interface SeedProduct { name: string; category: string; brand: string | null; offers: Array<{ supplier: string; price: number; stars: number; unit: string }> }

export const SEED_PRODUCTS: SeedProduct[] = [
  { name: 'ACDELCO 10W-30', category: 'ACEITE', brand: 'ACDELCO', offers: [
    { supplier: 'AUTOZONE', price: 60, stars: 5, unit: 'Litro' },
    { supplier: 'OREALLI', price: 500, stars: 3, unit: 'Garrafa' },
    { supplier: 'CHEVROLET', price: 80, stars: 4, unit: 'Litro' },
  ] },
  { name: 'CASTROL', category: 'ACEITE', brand: 'CASTROL', offers: [] },
  { name: 'MOTORCRAFT', category: 'ACEITE', brand: 'MOTORCRAFT', offers: [] },
  { name: 'MOBIL 5W-30 SINTÉTICO FULL', category: 'ACEITE', brand: 'MOBIL', offers: [] },
  { name: 'MOBIL 10W-30 MINERAL', category: 'ACEITE', brand: 'MOBIL', offers: [] },
  { name: 'BALERO DOBLE', category: 'BALERO DOBLE', brand: null, offers: [
    { supplier: 'DC', price: 550, stars: 5, unit: 'Pieza' },
    { supplier: 'AUTOZONE', price: 500, stars: 2, unit: 'Pieza' },
    { supplier: 'OREALLI', price: 600, stars: 3, unit: 'Pieza' },
    { supplier: 'CHEVROLET', price: 1000, stars: 4, unit: 'Pieza' },
  ] },
];
